[Distribution]
Distribution=arch
Architecture=x86-64

[Output]
Format=uki
ImageId=epsilon

[Content]
SourceDateEpoch=0

Packages=
  amd-ucode
  clevis
  cryptsetup
  curl
  efibootmgr
  intel-ucode
  linux
  lvm2
  man-db
  miniupnpc
  neovim
  net-tools
  systemd
  sbctl

Hostname=Epsilon
Keymap=us
Locale=C.UTF-8
Timezone=Etc/UTC
Autologin=true
